import scala.sys.process.Process

scalaTsFastOpt / logLevel := Level.Info

val npmReinstallAndTest = taskKey[Unit]("Reinstalls node modules and executes tests")

lazy val root = (project in file("."))
  .enablePlugins(ScalaTsPlugin, ScalablyTypedConverterExternalNpmPlugin)
  .settings(
    scalaVersion := "2.13.3",
    version := "0.0.1-SNAPSHOT",
    name := "scala-ts-e2e-dts",
    organization := "eu.swdev",
    scalaTsModuleName := "scala-ts-mod",
    scalaTsValidate := true,
    // enable adapter in order to include scala-ts-runtime library
    scalaTsAdapterEnabled := true,
    (crossTarget in fastOptJS) := (baseDirectory in Compile).value / "target" / "node_module",
    (crossTarget in fullOptJS) := (baseDirectory in Compile).value / "target" / "node_module",
    // scalaTsChangeForkOptions := withDebugForkOptions(5005),
    test := {
      // tests depend on ScalaTs output
      scalaTsFastOpt.value
      val r = (
        Process(Seq("npm", "t"), baseDirectory.value, "PATH" -> System.getenv("PATH")) !
      )
      if (r != 0) {
        throw new MessageOnlyException("e2e tests failed")
      }
    },
    npmReinstallAndTest := {
      // tests depend on ScalaTs output
      scalaTsFastOpt.value
      // when run by the ScriptedPlugin the node modules have to be reinstalled in the temporary project folder
      // -> remove the node_modules folder and run "npm i" before executing the tests
      val r = (
        Process(Seq("rm", "-rf", "node_modules"), baseDirectory.value, "PATH" -> System.getenv("PATH")) #&&
          Process(Seq("rm", "-f", "package-lock.json"), baseDirectory.value, "PATH" -> System.getenv("PATH")) #&&
          Process(Seq("npm", "i"), baseDirectory.value, "PATH" -> System.getenv("PATH")) #&&
          Process(Seq("npm", "t"), baseDirectory.value, "PATH" -> System.getenv("PATH")) !
        )
      if (r != 0) {
        throw new MessageOnlyException("e2e dts tests failed")
      }
    },
    externalNpm := {
      // this command is called before the scala-ts module is generated by the ScalablyTypedConverterExternalNpmPlugin
      // -> npm would fail if it would try to install the scala-ts-mod module
      // -> the scala-ts-mod module is configured as a devDependency
      // -> instruct npm to install production dependencies only
      Process(Seq("npm", "i", "--production"), baseDirectory.value).!
      baseDirectory.value
    },
//    scalaTsChangeForkOptions := withDebugForkOptions(5005)
  )
